### ISSUE TITLE
请问预测到对应的label怎么找呢

### ISSUE THREAD

**Issue by python1878** [AmemiyaYuko/HandwrittenChineseCharacterRecognition#3]
作者你好，我测试了一个图片文字，然后得到了预测结果：
Probability: 0.95431 with label:800
Probability: 0.01258 with label:810
Probability: 0.01235 with label:798

但是无法知道label800对应的中文是多少，谢谢。

**Comment by AmemiyaYuko** [comment]
可能需要您把数据集下下来，之后如果有空的话我会更新一个dict
